version: 3.0.0-beta.1 build {build}
max_jobs: 1

image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
clone_depth: 1
cache:
  - packages -> **\packages.config

platform: Any CPU
configuration:
  - Release

build:
  parallel: false
  project: SinsDataConverter.sln
  verbosity: minimal
before_build:
  - nuget restore

test: off

artifacts:
  - path: SinsDataConverter.Installer\bin\Release\SinsDataConverter-Installer.msi

deploy: off
