version: 3.0.0.{build}
max_jobs: 1
skip_commits:
  message: /^docs/

image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
clone_depth: 1
cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "3.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration:
  - Release

build:
  parallel: false
  project: SinsDataConverter.sln
  verbosity: minimal
before_build:
  - nuget restore
after_build:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Rename-Item "SinsDataConverter.Installer\bin\Release\SinsDataConverter-Installer.msi" "SinsDataConverter-$env:APPVEYOR_REPO_TAG_NAME.msi"
      }
      else
      {
        Rename-Item "SinsDataConverter.Installer\bin\Release\SinsDataConverter-Installer.msi" "SinsDataConverter-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_VERSION.msi"
      }

test: off

artifacts:
  - path: '**\*.msi'

deploy:
  - provider: GitHub
    auth_token:
      secure: VqgrP/Fg6/6IUKNvLW5ifXMXDvnMZqfGpeeNvNB4u7Z4bUpW/sXOw7G+L0174GLo
    description: ''
    artifact: /.*\.msi/
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true
