version: 3.0.0.{build}
max_jobs: 1

image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
clone_depth: 1
cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "3.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU
configuration:
  - Release

build:
  parallel: false
  project: SinsDataConverter.sln
  verbosity: minimal
before_build:
  - nuget restore

test: off

artifacts:
  - path: SinsDataConverter.Installer\bin\Release\SinsDataConverter-Installer.msi

deploy: off
