theme: jekyll-theme-midnight
title: [Sins Data Converter]
description: [A small Windows utility that allows easy two-way conversion between BIN and TXT for game data files of Sins of a Solar Empire by Ironclad Games]
